// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNnIFLEWIs27J4p_-HnUmtbAT2G0utoAs',
    appId: '1:48469250724:web:fba21e2c9ccdba6d084c31',
    messagingSenderId: '48469250724',
    projectId: 'flutter-auth-app-a0c0c',
    authDomain: 'flutter-auth-app-a0c0c.firebaseapp.com',
    storageBucket: 'flutter-auth-app-a0c0c.firebasestorage.app',
    measurementId: 'G-CDC5N7V7SW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmUOT4lR6sY9XK6t4F6nQQK8DaeopmTbM',
    appId: '1:48469250724:android:e9d920f43c896c0b084c31',
    messagingSenderId: '48469250724',
    projectId: 'flutter-auth-app-a0c0c',
    storageBucket: 'flutter-auth-app-a0c0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD5EHmPQLKxnOtjQPawOEPDQ1iDTv9r3g',
    appId: '1:48469250724:ios:0fc0e11b17c7fb4a084c31',
    messagingSenderId: '48469250724',
    projectId: 'flutter-auth-app-a0c0c',
    storageBucket: 'flutter-auth-app-a0c0c.firebasestorage.app',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD5EHmPQLKxnOtjQPawOEPDQ1iDTv9r3g',
    appId: '1:48469250724:ios:0fc0e11b17c7fb4a084c31',
    messagingSenderId: '48469250724',
    projectId: 'flutter-auth-app-a0c0c',
    storageBucket: 'flutter-auth-app-a0c0c.firebasestorage.app',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNnIFLEWIs27J4p_-HnUmtbAT2G0utoAs',
    appId: '1:48469250724:web:81c77017678b13bc084c31',
    messagingSenderId: '48469250724',
    projectId: 'flutter-auth-app-a0c0c',
    authDomain: 'flutter-auth-app-a0c0c.firebaseapp.com',
    storageBucket: 'flutter-auth-app-a0c0c.firebasestorage.app',
    measurementId: 'G-JW5470D4NM',
  );
}
